#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::NetworksDB;

my $type = pop @ARGV;
my @parts = @ARGV;
my $ndb = esmith::NetworksDB->open_ro() || die('Could not open NetworksDB');

foreach my $zone ($ndb->zones()) {
    if(grep { $zone->prop('Interface') eq $_ } @parts) {
        printf("Interface %s is referenced by zone %s\n", $zone->prop('Interface'), $zone->key);
        exit(3);
    }
}

exit(0);
